---
apiVersion: v1
kind: Service
metadata:
  name: data-marketplace-facade-service
  labels:
    app: data-marketplace-facade
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  type: LoadBalancer
  selector:
    app: data-marketplace-facade
