---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: data-marketplace-facade-deployment
spec:
  selector:
    matchLabels:
      app: data-marketplace-facade
  replicas: 1
  template:
    metadata:
      labels:
        app: data-marketplace-facade
    spec:
      containers:
      - name: data-marketplace-facade
        image: lgsvlfx/data-marketplace-facade:ci
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: CHAIN_SERVICE_HOST
          value: "http://chaincode-rest-service:9090/"



